# Generated by Django 4.2.29 on 2026-03-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelproject',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
